# Generated by Django 2.2.1 on 2019-08-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=250)),
                ('debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree', models.DurationField(null=True)),
            ],
            options={
                'ordering': ['patient', 'debut'],
            },
        ),
        migrations.CreateModel(
            name='Clinicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoProfil', models.ImageField(default='CliniciensPics/image.png', upload_to='./Media/photosProfilsCliniciens/')),
            ],
            options={
                'ordering': ['equipe'],
                'permissions': (('Clinicien_Responsable', "Responsable d'équipe clinicienne"),),
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['enAttente__dateFin'],
            },
        ),
        migrations.CreateModel(
            name='enAttente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordreAtteint', models.SmallIntegerField(default=1)),
                ('repetition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dateVisible', models.DateField(default=django.utils.timezone.now)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('isAnalyse', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'ordering': ['patient', 'dateFin', 'dateVisible'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('isClinicien', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_clinicien', to='user.Clinicien')),
            ],
            options={
                'ordering': ['patient', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('duree', models.DurationField(null=True)),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
        migrations.CreateModel(
            name='variableEtude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStatistique', models.IntegerField(choices=[(1, 'discrete'), (2, 'continu')])),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('isImportante', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponseLibre', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enAttente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.enAttente')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Question')),
                ('reponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OneReponse', to='module.Reponse')),
                ('reponses', models.ManyToManyField(blank=True, related_name='ManyReponses', to='module.Reponse')),
            ],
            options={
                'ordering': ['enAttente', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField(choices=[(1, 'Equipe de clinicien'), (2, 'Groupe semi-séquentiel'), (3, 'Groupe séquentiel'), (4, 'Groupe non séquentiel'), (5, 'Groupe non suivie')])),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admet_une_sequence_tel_que', to='module.Sequence')),
            ],
            options={
                'ordering': ['categorie'],
                'permissions': (('parcours_Clinicien', "Possibilité de parcours d'un clinicien"), ('parcours_Patient_Suivie', "Possibilité de parcours d'un patient suivie"), ('parcours_Patient_Non_Suivie', "Possibilité de parcours d'un patient non suivie")),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastScore', models.IntegerField(blank=True, null=True)),
                ('NoSeeMsgQuantity', models.IntegerField(default=0)),
                ('universite', models.CharField(max_length=200)),
                ('parcours', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('skype', models.CharField(blank=True, max_length=20, null=True)),
                ('point', models.IntegerField(default=0)),
                ('dateFinTherapie', models.DateField(blank=True, null=True)),
                ('agenda', models.ManyToManyField(related_name='Agenda', through='user.Agenda', to='user.Clinicien')),
                ('clinicienACharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicien_du_patient', to='user.Clinicien')),
                ('groupePatients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Population')),
                ('message', models.ManyToManyField(related_name='Message', through='user.Message', to='user.Clinicien')),
                ('section', models.ManyToManyField(through='user.Parcours', to='module.Section')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Sequence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variable', models.ManyToManyField(through='user.Dossier', to='user.variableEtude')),
            ],
            options={
                'ordering': ['clinicienACharge', 'groupePatients'],
            },
        ),
        migrations.AddField(
            model_name='parcours',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_parcours', to='user.Patient'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Section'),
        ),
        migrations.AddField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_patient', to='user.Patient'),
        ),
        migrations.AddField(
            model_name='enattente',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Patient'),
        ),
        migrations.AddField(
            model_name='enattente',
            name='reponse',
            field=models.ManyToManyField(through='user.Resultat', to='module.Reponse'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='enAttente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.enAttente'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.variableEtude'),
        ),
        migrations.AddField(
            model_name='clinicien',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integre', to='user.Population'),
        ),
        migrations.AddField(
            model_name='clinicien',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='clinicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_clini', to='user.Clinicien'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_patient', to='user.Patient'),
        ),
    ]
