# Generated by Django 2.2.1 on 2019-07-17 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='enAttente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.enAttente'),
        ),
    ]
