# Generated by Django 2.2.1 on 2019-05-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clinicien_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicien',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id_patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Clinicien',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
