# Generated by Django 2.2.1 on 2019-08-21 14:12

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='imageModule/')),
                ('nbSection', models.PositiveSmallIntegerField(default=0)),
                ('isVisible', models.BooleanField(default=False)),
                ('isQuestionnaireOnly', models.BooleanField(default=False)),
                ('isJournal', models.BooleanField(default=False)),
                ('questionnaireDependant', models.ForeignKey(blank=True, limit_choices_to={'isQuestionnaireOnly': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'ordering': ['sequence', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputType', models.IntegerField(choices=[(1, 'Selectionner une réponse ou plusieurs réponses'), (2, 'Bouton radio'), (3, 'Case à cocher (réponse multiple)'), (4, 'Reponse texte libre'), (5, 'Reponse gradué libre')])),
                ('isMultipleRep', models.BooleanField(choices=[(True, 'Plusieurs choix de réponses possibles'), (False, 'Une seul réponse')], default=False)),
                ('isRequired', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=250)),
                ('consigne', models.CharField(blank=True, max_length=250, null=True)),
                ('intervaleGraduerInput', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('nbModule', models.PositiveSmallIntegerField(default=0)),
                ('possede', models.ManyToManyField(blank=True, through='module.Ordre', to='module.Module')),
            ],
            options={
                'permissions': (('Sequence_Groupal', 'Affecter une sequence de façon groupale'), ('Sequence_Individuel', 'Affecter une sequence de façon individuelle')),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('SectionType', models.IntegerField(choices=[(1, 'Texte et images'), (2, 'Question'), (3, 'Vidéo')])),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Question')),
            ],
            options={
                'ordering': ['module', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=250)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Question')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.AddField(
            model_name='ordre',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Sequence'),
        ),
    ]
